set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/log2//LOG2_G4_5_3389.sp"
cellgen select LOG2_G4_5_3389
cellgen autoflow
export layout LOG2_G4_5_3389 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/log2//LOG2_G4_5_3389.gds
exit
    
