set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/ctrl//CTRL_G4_4_8_13_65.sp"
cellgen select CTRL_G4_4_8_13_65
cellgen autoflow
export layout CTRL_G4_4_8_13_65 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/ctrl//CTRL_G4_4_8_13_65.gds
exit
    
