set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/log2//LOG2_G2_4_7531.sp"
cellgen select LOG2_G2_4_7531
cellgen autoflow
export layout LOG2_G2_4_7531 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/log2//LOG2_G2_4_7531.gds
exit
    
