set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05_5/voter//VOTER_G3_12_13.sp"
cellgen select VOTER_G3_12_13
cellgen autoflow
export layout VOTER_G3_12_13 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05_5/voter//VOTER_G3_12_13.gds
exit
    
