set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/square//SQUARE_G1_2_6.sp"
cellgen select SQUARE_G1_2_6
cellgen autoflow
export layout SQUARE_G1_2_6 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/square//SQUARE_G1_2_6.gds
exit
    
