set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/int2float//INT2FLOAT_G3_0_3.sp"
cellgen select INT2FLOAT_G3_0_3
cellgen autoflow
export layout INT2FLOAT_G3_0_3 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/int2float//INT2FLOAT_G3_0_3.gds
exit
    
