set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/sqrt//SQRT_G4_14_44.sp"
cellgen select SQRT_G4_14_44
cellgen autoflow
export layout SQRT_G4_14_44 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/sqrt//SQRT_G4_14_44.gds
exit
    
