set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/sqrt//SQRT_G1_1_67.sp"
cellgen select SQRT_G1_1_67
cellgen autoflow
export layout SQRT_G1_1_67 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/sqrt//SQRT_G1_1_67.gds
exit
    
