set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/sqrt//SQRT_G3_1_166.sp"
cellgen select SQRT_G3_1_166
cellgen autoflow
export layout SQRT_G3_1_166 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/sqrt//SQRT_G3_1_166.gds
exit
    
