set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/max//MAX_G2_3_2012.sp"
cellgen select MAX_G2_3_2012
cellgen autoflow
export layout MAX_G2_3_2012 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/max//MAX_G2_3_2012.gds
exit
    
