set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/max//MAX_G1_2_9.sp"
cellgen select MAX_G1_2_9
cellgen autoflow
export layout MAX_G1_2_9 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/max//MAX_G1_2_9.gds
exit
    
