set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/multiplier//MULTIPLIER_G0_2_27.sp"
cellgen select MULTIPLIER_G0_2_27
cellgen autoflow
export layout MULTIPLIER_G0_2_27 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/multiplier//MULTIPLIER_G0_2_27.gds
exit
    
