set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/square//SQUARE_G2_2_28.sp"
cellgen select SQUARE_G2_2_28
cellgen autoflow
export layout SQUARE_G2_2_28 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/square//SQUARE_G2_2_28.gds
exit
    
