set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/square//SQUARE_G3_13_63_113_114.sp"
cellgen select SQUARE_G3_13_63_113_114
cellgen autoflow
export layout SQUARE_G3_13_63_113_114 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/square//SQUARE_G3_13_63_113_114.gds
exit
    
