set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/div//DIV_G3_346_448.sp"
cellgen select DIV_G3_346_448
cellgen autoflow
export layout DIV_G3_346_448 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/div//DIV_G3_346_448.gds
exit
    
