set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/sin//SIN_G0_1_95.sp"
cellgen select SIN_G0_1_95
cellgen autoflow
export layout SIN_G0_1_95 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/sin//SIN_G0_1_95.gds
exit
    
