set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/sin//SIN_G2_541_2227.sp"
cellgen select SIN_G2_541_2227
cellgen autoflow
export layout SIN_G2_541_2227 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/sin//SIN_G2_541_2227.gds
exit
    
