set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/sin//SIN_G4_106_1233.sp"
cellgen select SIN_G4_106_1233
cellgen autoflow
export layout SIN_G4_106_1233 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/sin//SIN_G4_106_1233.gds
exit
    
