set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/i2c//I2C_G3_94_119.sp"
cellgen select I2C_G3_94_119
cellgen autoflow
export layout I2C_G3_94_119 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/i2c//I2C_G3_94_119.gds
exit
    
