set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/dec//DEC_G0_15_38.sp"
cellgen select DEC_G0_15_38
cellgen autoflow
export layout DEC_G0_15_38 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/dec//DEC_G0_15_38.gds
exit
    
