set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/arbiter//ARBITER_G2_0_769_770.sp"
cellgen select ARBITER_G2_0_769_770
cellgen autoflow
export layout ARBITER_G2_0_769_770 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/arbiter//ARBITER_G2_0_769_770.gds
exit
    
