set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/arbiter//ARBITER_G0_3_6683.sp"
cellgen select ARBITER_G0_3_6683
cellgen autoflow
export layout ARBITER_G0_3_6683 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/arbiter//ARBITER_G0_3_6683.gds
exit
    
