set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../stdCelllib/cellsAstranFriendly.sp"
cellgen select BUFX4
cellgen autoflow
export layout BUFX4 /home/flynn/workplace/CEMapping/src/originalAstranStdCells//BUFX4.gds
exit
    
