set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../stdCelllib/cellsAstranFriendly.sp"
cellgen select CLKBUF3
cellgen autoflow
export layout CLKBUF3 /home/flynn/workplace/CEMapping/src/originalAstranStdCells//CLKBUF3.gds
exit
    
