set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../stdCelllib/cellsAstranFriendly.sp"
cellgen select DFFNEGX1
cellgen autoflow
export layout DFFNEGX1 /home/flynn/workplace/CEMapping/src/originalAstranStdCells//DFFNEGX1.gds
exit
    
