set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../stdCelllib/cellsAstranFriendly.sp"
cellgen select DFFSR
cellgen autoflow
export layout DFFSR /home/flynn/workplace/CEMapping/src/originalAstranStdCells//DFFSR.gds
exit
    
