set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../stdCelllib/cellsAstranFriendly.sp"
cellgen select INVX2
cellgen autoflow
export layout INVX2 /home/flynn/workplace/CEMapping/src/originalAstranStdCells//INVX2.gds
exit
    
