set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../stdCelllib/cellsAstranFriendly.sp"
cellgen select OAI21X1
cellgen autoflow
export layout OAI21X1 /home/flynn/workplace/CEMapping/src/originalAstranStdCells//OAI21X1.gds
exit
    
