set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/mem_ctrl//MEM_CTRL_G2_154_262.sp"
cellgen select MEM_CTRL_G2_154_262
cellgen autoflow
export layout MEM_CTRL_G2_154_262 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/mem_ctrl//MEM_CTRL_G2_154_262.gds
exit
    
