set lpsolve "/home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/outputs/router//COMPLEX1.sp"
cellgen select COMPLEX1
cellgen autoflow
export layout COMPLEX1 /home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/outputs/router//COMPLEX1.gds
exit
    
