set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05_5/ctrl//CTRL_G1_68_69.sp"
cellgen select CTRL_G1_68_69
cellgen autoflow
export layout CTRL_G1_68_69 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05_5/ctrl//CTRL_G1_68_69.gds
exit
    
