set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05_5/ctrl//CTRL_G2_1_12_26_48.sp"
cellgen select CTRL_G2_1_12_26_48
cellgen autoflow
export layout CTRL_G2_1_12_26_48 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05_5/ctrl//CTRL_G2_1_12_26_48.gds
exit
    
