set lpsolve "/home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/outputs/multiplier//COMPLEX7.sp"
cellgen select COMPLEX7
cellgen autoflow
export layout COMPLEX7 /home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/outputs/multiplier//COMPLEX7.gds
exit
    
