set lpsolve "/home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/outputs/multiplier//COMPLEX26.sp"
cellgen select COMPLEX26
cellgen autoflow
export layout COMPLEX26 /home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/outputs/multiplier//COMPLEX26.gds
exit
    
