set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/bar//BAR_G0_9_337.sp"
cellgen select BAR_G0_9_337
cellgen autoflow
export layout BAR_G0_9_337 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/bar//BAR_G0_9_337.gds
exit
    
