set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05/voter//VOTER_G4_2569_2572_2581.sp"
cellgen select VOTER_G4_2569_2572_2581
cellgen autoflow
export layout VOTER_G4_2569_2572_2581 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05/voter//VOTER_G4_2569_2572_2581.gds
exit
    
