set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/ctrl//CTRL_G1_1_34.sp"
cellgen select CTRL_G1_1_34
cellgen autoflow
export layout CTRL_G1_1_34 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/ctrl//CTRL_G1_1_34.gds
exit
    
