set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/ctrl//CTRL_G2_13_52.sp"
cellgen select CTRL_G2_13_52
cellgen autoflow
export layout CTRL_G2_13_52 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/ctrl//CTRL_G2_13_52.gds
exit
    
