set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/ctrl//CTRL_G4_3_8_79.sp"
cellgen select CTRL_G4_3_8_79
cellgen autoflow
export layout CTRL_G4_3_8_79 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/ctrl//CTRL_G4_3_8_79.gds
exit
    
