set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/adder//ADDER_G0_454_455.sp"
cellgen select ADDER_G0_454_455
cellgen autoflow
export layout ADDER_G0_454_455 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/adder//ADDER_G0_454_455.gds
exit
    
