set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/adder//ADDER_G2_0_411.sp"
cellgen select ADDER_G2_0_411
cellgen autoflow
export layout ADDER_G2_0_411 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/adder//ADDER_G2_0_411.gds
exit
    
