set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/div//DIV_G3_0_27247.sp"
cellgen select DIV_G3_0_27247
cellgen autoflow
export layout DIV_G3_0_27247 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/div//DIV_G3_0_27247.gds
exit
    
