set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/arbiter//ARBITER_G3_2_768_769.sp"
cellgen select ARBITER_G3_2_768_769
cellgen autoflow
export layout ARBITER_G3_2_768_769 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/arbiter//ARBITER_G3_2_768_769.gds
exit
    
