set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/arbiter//ARBITER_G1_7_9.sp"
cellgen select ARBITER_G1_7_9
cellgen autoflow
export layout ARBITER_G1_7_9 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/arbiter//ARBITER_G1_7_9.gds
exit
    
