set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/arbiter//ARBITER_G2_0_424.sp"
cellgen select ARBITER_G2_0_424
cellgen autoflow
export layout ARBITER_G2_0_424 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/arbiter//ARBITER_G2_0_424.gds
exit
    
