set lpsolve "/home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/outputs/adder//COMPLEX10.sp"
cellgen select COMPLEX10
cellgen autoflow
export layout COMPLEX10 /home/flynn/workplace/CEMapping/AutoCellLibX/pySrc/outputs/adder//COMPLEX10.gds
exit
    
