set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/priority//PRIORITY_G1_625_626.sp"
cellgen select PRIORITY_G1_625_626
cellgen autoflow
export layout PRIORITY_G1_625_626 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/priority//PRIORITY_G1_625_626.gds
exit
    
