set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/priority//PRIORITY_G4_482_483.sp"
cellgen select PRIORITY_G4_482_483
cellgen autoflow
export layout PRIORITY_G4_482_483 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/priority//PRIORITY_G4_482_483.gds
exit
    
