set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/max//MAX_G3_3_5.sp"
cellgen select MAX_G3_3_5
cellgen autoflow
export layout MAX_G3_3_5 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/max//MAX_G3_3_5.gds
exit
    
