set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/router//ROUTER_G4_36_82.sp"
cellgen select ROUTER_G4_36_82
cellgen autoflow
export layout ROUTER_G4_36_82 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/router//ROUTER_G4_36_82.gds
exit
    
