set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/router//ROUTER_G1_38_39.sp"
cellgen select ROUTER_G1_38_39
cellgen autoflow
export layout ROUTER_G1_38_39 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/router//ROUTER_G1_38_39.gds
exit
    
