set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/sqrt//SQRT_G0_173_198_231_260.sp"
cellgen select SQRT_G0_173_198_231_260
cellgen autoflow
export layout SQRT_G0_173_198_231_260 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/sqrt//SQRT_G0_173_198_231_260.gds
exit
    
