set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05/arbiter//ARBITER_G3_2_3_6.sp"
cellgen select ARBITER_G3_2_3_6
cellgen autoflow
export layout ARBITER_G3_2_3_6 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05/arbiter//ARBITER_G3_2_3_6.gds
exit
    
