set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/cavlc//CAVLC_G2_3_6.sp"
cellgen select CAVLC_G2_3_6
cellgen autoflow
export layout CAVLC_G2_3_6 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/cavlc//CAVLC_G2_3_6.gds
exit
    
