set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/cavlc//CAVLC_G4_0_152.sp"
cellgen select CAVLC_G4_0_152
cellgen autoflow
export layout CAVLC_G4_0_152 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/cavlc//CAVLC_G4_0_152.gds
exit
    
