set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/cavlc//CAVLC_G1_0_63.sp"
cellgen select CAVLC_G1_0_63
cellgen autoflow
export layout CAVLC_G1_0_63 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.01/cavlc//CAVLC_G1_0_63.gds
exit
    
