set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/priority//PRIORITY_G0_0_1069.sp"
cellgen select PRIORITY_G0_0_1069
cellgen autoflow
export layout PRIORITY_G0_0_1069 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/priority//PRIORITY_G0_0_1069.gds
exit
    
