set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/priority//PRIORITY_G3_35_632_633.sp"
cellgen select PRIORITY_G3_35_632_633
cellgen autoflow
export layout PRIORITY_G3_35_632_633 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/priority//PRIORITY_G3_35_632_633.gds
exit
    
