set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/multiplier//MULTIPLIER_G2_10_8362.sp"
cellgen select MULTIPLIER_G2_10_8362
cellgen autoflow
export layout MULTIPLIER_G2_10_8362 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/multiplier//MULTIPLIER_G2_10_8362.gds
exit
    
