set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/i2c//I2C_G0_15_66.sp"
cellgen select I2C_G0_15_66
cellgen autoflow
export layout I2C_G0_15_66 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/i2c//I2C_G0_15_66.gds
exit
    
