set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/hyp//HYP_G2_7_10.sp"
cellgen select HYP_G2_7_10
cellgen autoflow
export layout HYP_G2_7_10 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/hyp//HYP_G2_7_10.gds
exit
    
