set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/hyp//HYP_G0_4_54564.sp"
cellgen select HYP_G0_4_54564
cellgen autoflow
export layout HYP_G0_4_54564 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/hyp//HYP_G0_4_54564.gds
exit
    
