set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/div//DIV_G4_397_398.sp"
cellgen select DIV_G4_397_398
cellgen autoflow
export layout DIV_G4_397_398 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/div//DIV_G4_397_398.gds
exit
    
