set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05/voter//VOTER_G4_29_36_37_64.sp"
cellgen select VOTER_G4_29_36_37_64
cellgen autoflow
export layout VOTER_G4_29_36_37_64 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05/voter//VOTER_G4_29_36_37_64.gds
exit
    
