set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/bar//BAR_G4_183_944_945.sp"
cellgen select BAR_G4_183_944_945
cellgen autoflow
export layout BAR_G4_183_944_945 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/bar//BAR_G4_183_944_945.gds
exit
    
