set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/arbiter//ARBITER_G3_1_2_1021_1022.sp"
cellgen select ARBITER_G3_1_2_1021_1022
cellgen autoflow
export layout ARBITER_G3_1_2_1021_1022 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/arbiter//ARBITER_G3_1_2_1021_1022.gds
exit
    
