set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/arbiter//ARBITER_G4_0_1_3_4.sp"
cellgen select ARBITER_G4_0_1_3_4
cellgen autoflow
export layout ARBITER_G4_0_1_3_4 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/arbiter//ARBITER_G4_0_1_3_4.gds
exit
    
