set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/ctrl//CTRL_G4_1_16_22_23.sp"
cellgen select CTRL_G4_1_16_22_23
cellgen autoflow
export layout CTRL_G4_1_16_22_23 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/ctrl//CTRL_G4_1_16_22_23.gds
exit
    
