set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05/dec//DEC_G4_0_164_165.sp"
cellgen select DEC_G4_0_164_165
cellgen autoflow
export layout DEC_G4_0_164_165 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05/dec//DEC_G4_0_164_165.gds
exit
    
