set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/dec//DEC_G0_1_2_3.sp"
cellgen select DEC_G0_1_2_3
cellgen autoflow
export layout DEC_G0_1_2_3 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/dec//DEC_G0_1_2_3.gds
exit
    
