set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05_5/nand_nor//NAND_NOR_G0_0_1.sp"
cellgen select NAND_NOR_G0_0_1
cellgen autoflow
export layout NAND_NOR_G0_0_1 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05_5/nand_nor//NAND_NOR_G0_0_1.gds
exit
    
