set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05/arbiter//ARBITER_G4_0_171_6738.sp"
cellgen select ARBITER_G4_0_171_6738
cellgen autoflow
export layout ARBITER_G4_0_171_6738 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K3/0.05/arbiter//ARBITER_G4_0_171_6738.gds
exit
    
