set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/bar//BAR_G2_34_41.sp"
cellgen select BAR_G2_34_41
cellgen autoflow
export layout BAR_G2_34_41 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/bar//BAR_G2_34_41.gds
exit
    
