set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/i2c//I2C_G3_80_81.sp"
cellgen select I2C_G3_80_81
cellgen autoflow
export layout I2C_G3_80_81 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/i2c//I2C_G3_80_81.gds
exit
    
