set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/sin//SIN_G3_34_49_294_295.sp"
cellgen select SIN_G3_34_49_294_295
cellgen autoflow
export layout SIN_G3_34_49_294_295 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/sin//SIN_G3_34_49_294_295.gds
exit
    
