set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/div//DIV_G0_202_203_21066.sp"
cellgen select DIV_G0_202_203_21066
cellgen autoflow
export layout DIV_G0_202_203_21066 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/div//DIV_G0_202_203_21066.gds
exit
    
