set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/bar//BAR_G0_3_26_30_31.sp"
cellgen select BAR_G0_3_26_30_31
cellgen autoflow
export layout BAR_G0_3_26_30_31 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/bar//BAR_G0_3_26_30_31.gds
exit
    
