set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/arbiter//ARBITER_G1_10_1104.sp"
cellgen select ARBITER_G1_10_1104
cellgen autoflow
export layout ARBITER_G1_10_1104 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/arbiter//ARBITER_G1_10_1104.gds
exit
    
