set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/bar//BAR_G0_0_2023_2028.sp"
cellgen select BAR_G0_0_2023_2028
cellgen autoflow
export layout BAR_G0_0_2023_2028 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/bar//BAR_G0_0_2023_2028.gds
exit
    
