set lpsolve "/home/flynn/workplace/CEMapping/src/../tools/gurobi/bin/gurobi_cl"
load technology "/home/flynn/workplace/CEMapping/src/../tools/astran/Astran/build/Work/tech_freePDK45.rul"
load netlist "/home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/sqrt//SQRT_G3_132_134.sp"
cellgen select SQRT_G3_132_134
cellgen autoflow
export layout SQRT_G3_132_134 /home/flynn/workplace/CEMapping/src/../outputs/Astran/K4/0.01/sqrt//SQRT_G3_132_134.gds
exit
    
